# Generated by Django 3.2.4 on 2021-11-17 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.AutoField(db_column='studentId', primary_key=True, serialize=False)),
                ('studentfirstname', models.CharField(db_column='studentFirstName', max_length=45)),
                ('studentphonenumber', models.CharField(db_column='studentPhoneNumber', max_length=45)),
                ('studentlastname', models.CharField(blank=True, db_column='studentLastName', max_length=45, null=True)),
                ('studentemailid', models.EmailField(db_column='studentEmailId', max_length=45)),
                ('studentpassword', models.CharField(db_column='studentPassword', max_length=45)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
